# Generated by Django 6.0.6 on 2026-07-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('marital_status', models.IntegerField()),
                ('application_mode', models.IntegerField()),
                ('application_order', models.IntegerField()),
                ('course', models.IntegerField()),
                ('daytime_evening_attendance', models.IntegerField()),
                ('previous_qualification', models.IntegerField()),
                ('admission_grade', models.FloatField()),
                ('displaced', models.IntegerField()),
                ('educational_special_needs', models.IntegerField()),
                ('debtor', models.IntegerField()),
                ('tuition_fees_up_to_date', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('scholarship_holder', models.IntegerField()),
                ('age_at_enrollment', models.IntegerField()),
                ('curricular_units_1st_sem_approved', models.IntegerField()),
                ('curricular_units_2nd_sem_approved', models.IntegerField()),
                ('prediction', models.CharField(max_length=20)),
            ],
        ),
    ]
