# Generated by Django 6.0.6 on 2026-07-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='admission_grade',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='age_at_enrollment',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='application_mode',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='application_order',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='course',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='curricular_units_1st_sem_approved',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='curricular_units_2nd_sem_approved',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='daytime_evening_attendance',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='displaced',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='educational_special_needs',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='previous_qualification',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='scholarship_holder',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='tuition_fees_up_to_date',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='input_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
